name: flutter_weather
description: Flutter版假装看天气

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: any
  dio: any
  shared_preferences: any
  device_info: any
  rxdart: any
  intl: any
  flutter_staggered_grid_view: any
  url_launcher: any
  cached_network_image: any
  fluttertoast: 2.0.8
  pull_to_refresh: any
  image_picker: any
  connectivity: any

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # 图片
    - images/100.png
    - images/101.png
    - images/102.png
    - images/103.png
    - images/104.png
    - images/200.png
    - images/201.png
    - images/202.png
    - images/203.png
    - images/204.png
    - images/205.png
    - images/206.png
    - images/207.png
    - images/208.png
    - images/209.png
    - images/210.png
    - images/211.png
    - images/212.png
    - images/213.png
    - images/300.png
    - images/301.png
    - images/302.png
    - images/303.png
    - images/304.png
    - images/305.png
    - images/306.png
    - images/307.png
    - images/308.png
    - images/309.png
    - images/310.png
    - images/311.png
    - images/312.png
    - images/313.png
    - images/400.png
    - images/401.png
    - images/402.png
    - images/403.png
    - images/404.png
    - images/405.png
    - images/406.png
    - images/407.png
    - images/500.png
    - images/501.png
    - images/502.png
    - images/503.png
    - images/504.png
    - images/507.png
    - images/508.png
    - images/900.png
    - images/901.png
    - images/999.png

    # json文件
    - jsons/weather_map.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
